### ISSUE TITLE
Size Mismatch

### ISSUE THREAD

**Issue by YiqinZhao** [google-research/3d-moments#1]
I'm trying to run the demo with the instruction given by README. But I got the following errors. Is there a specific code change needed? Thanks!

```
Traceback (most recent call last):
  File "demo.py", line 248, in <module>
    render(args)
  File "demo.py", line 197, in render
    model = SpaceTimeModel(args)
  File "/home/yiqinzhao/Documents/3d-moments/model.py", line 112, in __init__
    load_scheduler=load_scheduler)
  File "/home/yiqinzhao/Documents/3d-moments/model.py", line 185, in load_from_ckpt
    self.load_model(fpath, load_opt, load_scheduler)
  File "/home/yiqinzhao/Documents/3d-moments/model.py", line 158, in load_model
    self.feature_net.load_state_dict(to_load['feature_net'])
  File "/home/yiqinzhao/miniconda3/envs/3d_moments/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResUNet:
        size mismatch for conv1.weight: copying a param with shape torch.Size([64, 5, 7, 7]) from checkpoint, the shape in current model is torch.Size([64, 4, 7, 7]).
```

**Comment by qianqianwang68** [comment]
Hi Yiqin, apologies for the confusion. The link we provided for downloading the pretrained model was not updated to the right version. Please re-download the pretrained model (`gdown https://drive.google.com/uc?id=1keqdnl2roBO2MjXhbd0VbfYaGAhyjUed -O pretrained/`) and run the demo again.
